### ISSUE TITLE
如何加速nms

### ISSUE THREAD

**Issue by piedaochuan1234** [zhouyuangan/quad-nms-cpu#1]
如题，我这边发现nms后处理占用很大一部分耗时。我c++水平很差，请问有什么好的办法、工具、思路加速nms吗？

**Comment by yy9568** [comment]
@piedaochuan1234 你可以使用cython+pyclipper的方案来替换c++&clipper的方案，先用python&pyclipper实现一个最基础的nms功能，改写为cython后进行编译

**Comment by piedaochuan1234** [comment]
> 

感谢回复,我去试试
